### ISSUE TITLE
[chalkboard] Add a way to customize brush

### ISSUE THREAD

**Issue by superbobry** [rajgoel/reveal.js-plugins#15]
There is a way to cutomize pen/chalk image but not so for the brush. Is this an intentional limitation?

**Comment by rajgoel** [comment]
It is indeed a somehow intentional limitation. The difference is that the pen will always draw at the mouse coordinates, whatever the image. The sponge shall delete what is below the sponge-image. By changing the image, the area deleted could not match the shape and size of the sponge. Adding customisation is thus not as easy. But if you find a nice way to add customisation, please let me know or create a PR.

**Comment by superbobry** [comment]
> By changing the image, the area deleted could not match the shape and size of the sponge.

I've been using `cursor: grab` for a while without changing anything else in the code (so it still deletes the area under the sponge) and I should say it felt OK. So although the shape mismatch looks like an issue in theory, in practice it hardly is.

I've also replaced the pen image with `cursor: crosshair` to make it less noticeable. This required pulling all the `url(...)` from the code into the options, e.g. the defaults now look like

```
{
  pen:  [ 'url("reveal.js-plugins/chalkboard/img/boardmarker.png")', 
          'url("reveal.js-plugins/chalkboard/img/chalk.png")' ]
}
```

 I could submit a PR if you're interested.

**Comment by rajgoel** [comment]
Yes, please. Would be great if you can create a PR. I also need to have a final look at your other open PR, but haven't found the time yet :-(

**Comment by rajgoel** [comment]
Just realised that using the default cursors instead of the sponge would not work on touchscreens because an image is shown instead of the cursor.
