### ISSUE TITLE
[chalkboard] Change Chalk and pen color on the fly

### ISSUE THREAD

**Issue by therimalaya** [rajgoel/reveal.js-plugins#23]
I like this chalkboard feature very much. I want to request a feature to change the chalk and pen colour during the presentation. Also, a shortcut to delete (or undo) recent draw will be awesome.

**Comment by rajgoel** [comment]
Hi, I'm glad you like the plugin. A color configuration makes sense and should be easy to add. Undo feature will be more complicated because undo requires to redraw the canvas (also needs some thinking with playback compatibility ...). Will keep these in mind when I find time to work on the plugin again.

**Comment by rinnert** [comment]
Hey, this is quite an old issue by now, yet I really wanted this feature -- so I have implemented it.

Let me know if yo are interested in a PR, ready any time.

**Comment by bcouetil** [comment]
I'm still very interested, please !

**Comment by rinnert** [comment]
> I'm still very interested, please !

I have filed the PR. I have no idea whether or when @rajgoel will accept or release this. Meanwhile, you can just grab it from my repository. You just need to put the ```img/``` folder and ```chalkboard.js``` into the proper location and add the key bindings suggested in the README.md to Reveal (or RISE or anything else you are using this with). 

Enjoy!

**Comment by rajgoel** [comment]
Fixed

**Comment by bcouetil** [comment]
Tested, and loved it ! Many thanks.
