### ISSUE TITLE
unexpected behavior with zoom plugin 

### ISSUE THREAD

**Issue by Belloliva** [rajgoel/reveal.js-plugins#33]
Hi,

Thanks for the chalkboard plugin, it is very useful. I sometimes need to zoom on SVG image and annotate on them. I use the zoom plugin built in reveal.js but the chalkboard plugin does not work properly on zoomed object, it annotates on the wrong position. Do you think this can be a quick fix?

Abdellah
Thanks

**Comment by rajgoel** [comment]
The chalkboard plugin does not allow to anotate on objects within the slides, instead the plugin creates a layer on top of the slide on which the drawings are shown. If the slide content changes (or the view of the slide content), the drawing layer remains unchanged. Thus, there is no straight forward way to achieve compatibility with the zoom plugin.

**Comment by fuhrmanator** [comment]
I attached an animated GIF to show what happens when I try it on a Surface Pro with the latest Chrome. (Unfortunately the cursor is not recorded.) I trace the S in the unzoomed screen.  Then I alt-tap to zoom (it's correct!). Then I trace again the S (but can't see it). Then I alt-tap to zoom out, and we see that what was written during the zoomed mode is displayed incorrectly.

![vKTAfjOIHq](https://user-images.githubusercontent.com/7606540/82347391-8956de00-99c5-11ea-90a4-731128e5ee56.gif)

Can you explain your answer with what we see? It seems to work partially.

Is it possible that the Zoom plug-in be modified to also zoom your drawing layer (if it exists) so that drawing in zoomed mode will work properly?

**Comment by rajgoel** [comment]
Hi, thanks for your feedback. I never tested the combination of chalkboard and zoom plugins and didn't implement anything for support. The drawing canvas is on top of the slides. Whenever the browser window resizes, it redraws the drawing canvas to fit the screen. I'm not sure how exactly the zoom plugin works, but the partial support indicates that a similar mechanism might be used. A fix might be possible, but this would need some investigation of the interaction.
