### ISSUE TITLE
[audio-slideshow] Get TTS text from notes, not data-audio-text?

### ISSUE THREAD

**Issue by fghaas** [rajgoel/reveal.js-plugins#4]
Some speakers choose to write out their speaker notes out in full, using the upstream Notes plugin (https://github.com/hakimel/reveal.js/tree/master/plugin/notes). It would be excellent if audio slideshow had a facility to parse the notes (from `<aside class="notes">`, the `data-notes` slide attribute, or Markdown `Note:` content), and read them out. This could either replace the `data-audio-text` attribute, or be supported alongside that attribute.

**Comment by rajgoel** [comment]
Good idea. Already thought of doing this, but only was able to use the holiday time for working on the plugin. Probably I won't be able to find much time for this soon. If you want to create a PR, please do so. Would be nice to see this feature in the plugin.

The configuration parameter ```defaultText``` could be used as a switch to decide whether to generate TTS from slide text, notes, or not at all, e.g.  ```defaultText: "notes,slide"``` could indicate to use the notes text if it is available and fallback to the slide text otherwise, ```defaultText: "notes"``` could indicate to only use the notes text if it is available, and ```defaultText: "slide"``` or ```defaultText: "none"``` would generate the default text from the slide or not at all.  In any case the ```data-audio-text``` should be used if provided. Implementation would probably be similar to the implementation for the default text as it is now.

**Comment by rajgoel** [comment]
I just implemented a quick [hack](https://github.com/rajgoel/reveal.js-plugins/commit/73a4b8f72db75c37a4919b04bf5d0ef0f166a53f) that allows to use the slide note for TTS if the new ```defaultNotes``` parameter is set to true. This doesn't work for fragments, though.

**Comment by fghaas** [comment]
Nice, thank you!
