### ISSUE TITLE
[chalkboard] chalkboard one time use for slide

### ISSUE THREAD

**Issue by DPDmancul** [rajgoel/reveal.js-plugins#8]
In Mozilla Firefox 46.0 if you draw on the chalkboard or with the pen and then you change slide, when you return on the previous slide you aren't able to modify anything if you don't reset with backspace key.
Maybe it could be a feature (to protect previous drawing by editing) but I think it's a bug

**Comment by rajgoel** [comment]
This is a feature described [here](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard#configuration). If you set ```readOnly: false;``` when initializing the plugin you can continue drawing after returning to the slide. 

The reason for the default behaviour is that playback of drawings requires the timing for all lines. When returning to a slide the timing is no longer consistent.

**Comment by DPDmancul** [comment]
Thank you, I had misunderstood the doc

**Comment by rajgoel** [comment]
Ok, let me know if you find a better formulation in the documentation.

**Comment by fuhrmanator** [comment]
I, too, thought this was a bug for a long time. In my online courses I very often go back to previous slides and want to write again. I stopped using chalkboard because I just thought it was a bug. Unfortunately, it's not easy to toggle the setting when I use it inside the vscode-reveal extension (yet).

A useful feedback in the UI would be to have the pencil icon grayed out with a hover message explaining why you can't modify the slide.

**Comment by rajgoel** [comment]
Given that this feature was more confusing than helpful it is removed in the current version v4.1.3 and adding notes should work out of the box when going back to slides

**Comment by fuhrmanator** [comment]
Thanks - the extension for VSCode is using [an old version](https://github.com/evilz/vscode-reveal/issues/685) and hopefully will get some love soon - it's so nice to do reveal in markdown "live" in VSCode. Sorry for the noise.
